# Generated by Django 5.0 on 2025-11-12 11:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, editable=False, help_text='Автоматически генерируемый номер договора', max_length=50, unique=True, verbose_name='Номер договора')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('suspended', 'Приостановлен'), ('terminated', 'Расторгнут')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('signed_date', models.DateField(help_text='Дата подписания договора', verbose_name='Дата заключения')),
                ('activation_date', models.DateField(blank=True, help_text='Дата активации услуг', null=True, verbose_name='Дата активации')),
                ('termination_date', models.DateField(blank=True, help_text='Дата расторжения договора', null=True, verbose_name='Дата расторжения')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Текущий баланс абонента', max_digits=10, verbose_name='Баланс (₽)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Общая сумма начислений за весь период', max_digits=12, verbose_name='Общая стоимость (₽)')),
                ('next_billing_date', models.DateField(blank=True, help_text='Дата следующего автоматического списания абонентской платы', null=True, verbose_name='Дата следующего списания')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о договоре', null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('customer', models.ForeignKey(help_text='Абонент, заключивший договор', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customers.customer', verbose_name='Абонент')),
                ('tariff', models.ForeignKey(help_text='Выбранный тарифный план', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='tariffs.tariff', verbose_name='Тарифный план')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['number'], name='contracts_c_number_21c396_idx'), models.Index(fields=['status'], name='contracts_c_status_aa7a80_idx'), models.Index(fields=['customer', 'status'], name='contracts_c_custome_791003_idx'), models.Index(fields=['next_billing_date'], name='contracts_c_next_bi_1499b2_idx')],
            },
        ),
    ]
