# Generated by Django 5.0 on 2025-11-26 15:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Текущий баланс абонента",
                max_digits=10,
                verbose_name="Баланс (с)",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Общая сумма начислений за весь период",
                max_digits=12,
                verbose_name="Общая стоимость (с)",
            ),
        ),
    ]
