# Generated by Django 5.0 on 2025-11-26 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_alter_contract_balance_alter_contract_total_cost"),
        ("contracts", "0002_trafficmetric"),
    ]

    operations = []
