# Generated by Django 5.0 on 2025-11-12 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('document_type', models.CharField(choices=[('passport', 'Паспорт РФ'), ('foreign_passport', 'Загранпаспорт'), ('driver_license', 'Водительское удостоверение')], default='passport', max_length=20, verbose_name='Тип документа')),
                ('passport_series', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Серия должна содержать 4 цифры')], verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Номер должен содержать 6 цифр')], verbose_name='Номер паспорта')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$|^\\d{12}$', 'ИНН должен содержать 10 или 12 цифр')], verbose_name='ИНН')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес регистрации')),
                ('phone', models.CharField(db_index=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +7XXXXXXXXXX', regex='^\\+7\\d{10}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('blocked', 'Заблокирован'), ('archived', 'Архивный')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Абонент',
                'verbose_name_plural': 'Абоненты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['passport_series', 'passport_number'], name='customers_c_passpor_ce08b1_idx'), models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['status'], name='customers_c_status_ce44cf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('passport_series', 'passport_number'), name='unique_passport'),
        ),
    ]
