# Generated by Django 5.0 on 2025-11-26 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("individual", "Физическое лицо"),
                    ("organization", "Организация"),
                ],
                default="individual",
                max_length=20,
                verbose_name="Тип клиента",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="organization_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ИНН/БИН организации"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="organization_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Название организации",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("passport", "Паспорт гражданина КР"),
                    ("id_card", "ID-карта (улуттук паспорт)"),
                    ("driver_license", "Водительское удостоверение КР"),
                    ("foreign_passport", "Загранпаспорт"),
                ],
                default="passport",
                max_length=20,
                verbose_name="Тип документа",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="passport_number",
            field=models.CharField(
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]{4,12}$",
                        "Номер может содержать латинские буквы и цифры (4-12 символов)",
                    )
                ],
                verbose_name="Номер паспорта",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="passport_series",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]{2,10}$",
                        "Серия может содержать латинские буквы и цифры (2-10 символов)",
                    )
                ],
                verbose_name="Серия паспорта",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активный"),
                    ("suspended", "Приостановлен"),
                    ("blocked", "Заблокирован"),
                    ("archived", "Архивный"),
                ],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
