# Generated by Django 5.0 on 2025-11-12 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment', 'Пополнение'), ('charge', 'Списание'), ('refund', 'Возврат'), ('correction', 'Корректировка')], db_index=True, default='payment', max_length=20, verbose_name='Тип транзакции')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма платежа в рублях', max_digits=10, verbose_name='Сумма (₽)')),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата платежа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('success', 'Успешно'), ('failed', 'Отклонен'), ('refunded', 'Возвращен')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('bank_transfer', 'Банковский перевод'), ('mobile_payment', 'Мобильный платеж'), ('auto_payment', 'Автоплатеж'), ('system', 'Системная операция')], default='cash', max_length=20, verbose_name='Способ оплаты')),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='Уникальный идентификатор транзакции во внешней платежной системе', max_length=100, null=True, unique=True, verbose_name='ID транзакции')),
                ('description', models.TextField(blank=True, help_text='Назначение платежа или причина списания', null=True, verbose_name='Описание')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Дата и время, когда платеж был обработан', null=True, verbose_name='Дата обработки')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, help_text='Баланс договора после выполнения транзакции', max_digits=10, null=True, verbose_name='Баланс после операции (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('contract', models.ForeignKey(help_text='Договор, к которому относится платеж', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contracts.contract', verbose_name='Договор')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Сотрудник, обработавший платеж', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['contract', '-payment_date'], name='payments_pa_contrac_596dbf_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['transaction_type'], name='payments_pa_transac_d1d8d9_idx'), models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx')],
            },
        ),
    ]
