# Generated by Django 5.0 on 2025-11-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Сумма платежа в сомах",
                max_digits=10,
                verbose_name="Сумма (с)",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="balance_after",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Баланс договора после выполнения транзакции",
                max_digits=10,
                null=True,
                verbose_name="Баланс после операции (с)",
            ),
        ),
    ]
