# Generated by Django 5.0 on 2025-11-12 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Краткое описание проблемы', max_length=200, verbose_name='Тема')),
                ('description', models.TextField(help_text='Подробное описание проблемы или вопроса', verbose_name='Описание')),
                ('category', models.CharField(choices=[('technical', 'Технические проблемы'), ('billing', 'Вопросы по оплате'), ('tariff', 'Смена тарифа'), ('sim', 'Проблемы с SIM-картой'), ('complaint', 'Жалоба'), ('other', 'Прочее')], db_index=True, default='other', max_length=20, verbose_name='Категория')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('waiting', 'Ожидает ответа'), ('resolved', 'Решен'), ('closed', 'Закрыт')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], db_index=True, default='medium', max_length=20, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assigned_at', models.DateTimeField(blank=True, help_text='Дата назначения тикета на сотрудника', null=True, verbose_name='Дата назначения')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Дата решения проблемы', null=True, verbose_name='Дата решения')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Дата закрытия тикета', null=True, verbose_name='Дата закрытия')),
                ('resolution', models.TextField(blank=True, help_text='Описание решения проблемы', null=True, verbose_name='Решение')),
                ('notes', models.TextField(blank=True, help_text='Внутренние заметки сотрудников', null=True, verbose_name='Примечания')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Сотрудник, ответственный за решение тикета', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Назначен на')),
                ('contract', models.ForeignKey(blank=True, help_text='Договор, к которому относится обращение (если применимо)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='contracts.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(blank=True, help_text='Сотрудник, создавший тикет', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('customer', models.ForeignKey(help_text='Абонент, создавший обращение', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='customers.customer', verbose_name='Абонент')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='tickets_tic_custome_3bafbd_idx'), models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'), models.Index(fields=['priority'], name='tickets_tic_priorit_0bec9b_idx'), models.Index(fields=['assigned_to', 'status'], name='tickets_tic_assigne_e36302_idx'), models.Index(fields=['category'], name='tickets_tic_categor_fc7dd1_idx'), models.Index(fields=['-created_at'], name='tickets_tic_created_c2132d_idx')],
            },
        ),
    ]
