# Generated by Django 5.0 on 2025-11-12 11:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, help_text='Подробное описание тарифного плана', null=True, verbose_name='Описание')),
                ('monthly_fee', models.DecimalField(decimal_places=2, help_text='Ежемесячная абонентская плата в рублях', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Абонентская плата (₽/мес)')),
                ('minutes_included', models.IntegerField(default=0, help_text='Количество включенных минут в месяц (0 = безлимит)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минуты включены')),
                ('sms_included', models.IntegerField(default=0, help_text='Количество включенных SMS в месяц (0 = безлимит)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='SMS включены')),
                ('data_gb_included', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Объем включенного интернет-трафика в ГБ (0 = безлимит)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Интернет включен (ГБ)')),
                ('minute_overage_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Цена за минуту сверх включенных', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Стоимость минуты сверх лимита (₽)')),
                ('sms_overage_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Цена за SMS сверх включенных', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Стоимость SMS сверх лимита (₽)')),
                ('data_gb_overage_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Цена за 1 ГБ сверх включенного', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Стоимость 1 ГБ сверх лимита (₽)')),
                ('extra_options', models.JSONField(blank=True, default=dict, help_text='Дополнительные услуги и опции (JSON)', verbose_name='Дополнительные опции')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Неактивные тарифы скрыты для новых подключений, но существующие договоры продолжают действовать', verbose_name='Активен')),
                ('tariff_type', models.CharField(choices=[('prepaid', 'Предоплатный'), ('postpaid', 'Постоплатный')], default='prepaid', help_text='Предоплатный - списание до начала периода, постоплатный - после', max_length=20, verbose_name='Тип тарифа')),
                ('priority', models.IntegerField(default=0, help_text='Чем выше число, тем выше тариф в списке', verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='tariffs_tar_is_acti_f1142b_idx'), models.Index(fields=['tariff_type'], name='tariffs_tar_tariff__210405_idx'), models.Index(fields=['-priority'], name='tariffs_tar_priorit_44bd45_idx')],
            },
        ),
    ]
