# Generated by Django 5.0 on 2025-11-26 15:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tariffs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tariff",
            name="data_gb_overage_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Цена за 1 ГБ сверх включенного",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Стоимость 1 ГБ сверх лимита (с)",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="minute_overage_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Цена за минуту сверх включенных",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Стоимость минуты сверх лимита (с)",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="monthly_fee",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Ежемесячная абонентская плата в сомах",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Абонентская плата (с/мес)",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="sms_overage_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Цена за SMS сверх включенных",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Стоимость SMS сверх лимита (с)",
            ),
        ),
    ]
