# Generated by Django 5.0 on 2025-11-12 11:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(db_index=True, help_text='Уникальный идентификатор SIM-карты (19-20 цифр)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{19,20}$', 'ICCID должен содержать 19-20 цифр')], verbose_name='ICCID')),
                ('imsi', models.CharField(db_index=True, help_text='Идентификатор абонента в сети оператора (15 цифр)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{15}$', 'IMSI должен содержать 15 цифр')], verbose_name='IMSI')),
                ('msisdn', models.CharField(db_index=True, help_text='Номер телефона в формате +7XXXXXXXXXX', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\+7\\d{10}$', 'Номер должен быть в формате +7XXXXXXXXXX')], verbose_name='MSISDN (номер телефона)')),
                ('puk_code', models.CharField(blank=True, help_text='PUK-код для разблокировки SIM-карты', max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'PUK-код должен содержать 8 цифр')], verbose_name='PUK-код')),
                ('status', models.CharField(choices=[('free', 'Свободна'), ('active', 'Активна'), ('suspended', 'Приостановлена'), ('blocked', 'Заблокирована'), ('closed', 'Закрыта')], db_index=True, default='free', max_length=20, verbose_name='Статус')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата активации')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата деактивации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_card', to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'SIM-карта',
                'verbose_name_plural': 'SIM-карты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['iccid'], name='sims_sim_iccid_129574_idx'), models.Index(fields=['imsi'], name='sims_sim_imsi_339b7e_idx'), models.Index(fields=['msisdn'], name='sims_sim_msisdn_cb5b85_idx'), models.Index(fields=['status'], name='sims_sim_status_afdfb8_idx')],
            },
        ),
    ]
