# Generated by Django 5.0 on 2025-11-12 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='msisdn',
            field=models.CharField(db_index=True, help_text='Номер телефона в формате +996XXXXXXXXX (пример: +996550555555)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\+996\\d{9}$', 'Номер должен быть в формате +996XXXXXXXXX')], verbose_name='MSISDN (номер телефона)'),
        ),
    ]
